---
title: "cs100-fp-SL-1130"
author: "Silei Li"
date: "11/30/2019"
output: html_document
---


```{r setup, include=FALSE}
survey <- read.csv("C:/R/Final project/mental_health_in_tech_survey.csv")
library(dplyr)
library(ggplot2)
```


#```{r setup, include=FALSE}
#survey <- read.csv("https://github.com/marielpacada/mental-health-in-tech/blob/master/mental-health-in-tech-survey.csv")
#```

##### Data cleaning

```{r}
survey[survey$no_employees=="6/25/2019" ] <- as.factor(6-25)
survey[survey$no_employees=="1/5/2019" ] <- as.factor(1-5)
```

```{r}
diffgender <- unique(survey$Gender)
```

```{r}
#Male
survey$Gender<-replace(survey$Gender,survey$Gender=="M","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="m","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="male","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="Male ","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="maile","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="Mail","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="Man","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="Mal","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="Malr","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="msle","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="Make","Male")


#Female
survey$Gender<-replace(survey$Gender,survey$Gender=="F","Female")
survey$Gender<-replace(survey$Gender,survey$Gender=="f","Female")
survey$Gender<-replace(survey$Gender,survey$Gender=="female","Female")
survey$Gender<-replace(survey$Gender,survey$Gender=="Female ","Female")
survey$Gender<-replace(survey$Gender,survey$Gender=="Femake","Female")
survey$Gender<-replace(survey$Gender,survey$Gender=="Woman","Female")
survey$Gender<-replace(survey$Gender,survey$Gender=="woman","Female")

#Cis
#??partial match, do "fe" first for females, than "male" for males

#Cis female
survey$Gender<-replace(survey$Gender,survey$Gender=="Cis Female","Female")
survey$Gender<-replace(survey$Gender,survey$Gender=="cis-female/femme","Female")
survey$Gender<-replace(survey$Gender,survey$Gender=="Female (cis)","Female")
survey$Gender<-replace(survey$Gender,survey$Gender=="","Female")
survey$Gender<-replace(survey$Gender,survey$Gender=="","Female")

#Cis male
survey$Gender<-replace(survey$Gender,survey$Gender=="Cis Male","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="cis male","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="Cis Man","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="Male (CIS)","Male")
survey$Gender<-replace(survey$Gender,survey$Gender=="","Male")

#Trans

```

```{r}
diffgender <- unique(survey$Gender)
diffgender
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```